### ISSUE TITLE
将这个项目收录到重庆大学自由/开源软件目录

### ISSUE THREAD

**Issue by Hagb** [CQU-CSA/CQUScheduleCalendar#1]
作者你好。我们正在整理和重庆大学有关的自由/开源软件项目，并收录在重庆大学自由/开源软件目录 https://github.com/cqu-codehub/cqu-code-index 中。
请问是否愿意让这个项目被收录到该目录？
感谢！

**Comment by HBat11233** [comment]
> 作者你好。我们正在整理和重庆大学有关的自由/开源软件项目，并收录在重庆大学自由/开源软件目录 https://github.com/cqu-codehub/cqu-code-index 中。
> 请问是否愿意让这个项目被收录到该目录？
> 感谢！

可以的，

**Comment by Hagb** [comment]
已收录。由于旧教务网不再用于排课，收录到了归档中。
